import type { AssetItem, EmojiItem, ImageAsset, ImageCategory } from '../types';

// ============================================================
// 分割线素材
// ============================================================

export const DIVIDERS: AssetItem[] = [
  {
    id: 'divider-dotted',
    name: '虚线分割',
    category: 'divider',
    tags: ['虚线', 'dotted', '简约'],
    content: '\n<hr style="border: none; border-top: 2px dotted #ccc; margin: 20px 0;" />\n',
    preview: '<hr style="border: none; border-top: 2px dotted #ccc; margin: 10px 0;" />',
  },
  {
    id: 'divider-wave',
    name: '波浪线分割',
    category: 'divider',
    tags: ['波浪', 'wave', '曲线'],
    content: '\n<p style="text-align: center; color: #999; margin: 20px 0; font-size: 20px; letter-spacing: 8px;">〰〰〰〰〰〰〰〰</p>\n',
    preview: '<p style="text-align: center; color: #999; margin: 10px 0; font-size: 16px; letter-spacing: 6px;">〰〰〰〰〰〰〰〰</p>',
  },
  {
    id: 'divider-gradient',
    name: '渐变线分割',
    category: 'divider',
    tags: ['渐变', 'gradient', '彩色'],
    content: '\n<div style="height: 2px; margin: 20px 0; background: linear-gradient(to right, transparent, #667eea, #764ba2, transparent);"></div>\n',
    preview: '<div style="height: 2px; margin: 10px 0; background: linear-gradient(to right, transparent, #667eea, #764ba2, transparent);"></div>',
  },
  {
    id: 'divider-star',
    name: '星星分割',
    category: 'divider',
    tags: ['星星', 'star', '装饰'],
    content: '\n<p style="text-align: center; color: #f0c040; margin: 20px 0; font-size: 16px; letter-spacing: 12px;">✦ ✦ ✦ ✦ ✦</p>\n',
    preview: '<p style="text-align: center; color: #f0c040; margin: 10px 0; font-size: 14px; letter-spacing: 10px;">✦ ✦ ✦ ✦ ✦</p>',
  },
  {
    id: 'divider-flower',
    name: '花朵分割',
    category: 'divider',
    tags: ['花朵', 'flower', '可爱'],
    content: '\n<p style="text-align: center; color: #e91e63; margin: 20px 0; font-size: 16px; letter-spacing: 10px;">❀ ❀ ❀ ❀ ❀</p>\n',
    preview: '<p style="text-align: center; color: #e91e63; margin: 10px 0; font-size: 14px; letter-spacing: 8px;">❀ ❀ ❀ ❀ ❀</p>',
  },
  {
    id: 'divider-arrow',
    name: '箭头分割',
    category: 'divider',
    tags: ['箭头', 'arrow', '方向'],
    content: '\n<p style="text-align: center; color: #607d8b; margin: 20px 0; font-size: 16px; letter-spacing: 8px;">▸ ▸ ▸ ▸ ▸ ▸ ▸</p>\n',
    preview: '<p style="text-align: center; color: #607d8b; margin: 10px 0; font-size: 14px; letter-spacing: 6px;">▸ ▸ ▸ ▸ ▸ ▸ ▸</p>',
  },
  {
    id: 'divider-diamond',
    name: '菱形分割',
    category: 'divider',
    tags: ['菱形', 'diamond', '几何'],
    content: '\n<p style="text-align: center; color: #9c27b0; margin: 20px 0; font-size: 14px; letter-spacing: 10px;">◆ ◇ ◆ ◇ ◆ ◇ ◆</p>\n',
    preview: '<p style="text-align: center; color: #9c27b0; margin: 10px 0; font-size: 12px; letter-spacing: 8px;">◆ ◇ ◆ ◇ ◆ ◇ ◆</p>',
  },
  {
    id: 'divider-rainbow',
    name: '彩虹分割',
    category: 'divider',
    tags: ['彩虹', 'rainbow', '多彩'],
    content: '\n<div style="height: 4px; margin: 20px 0; background: linear-gradient(to right, #ff0000, #ff7700, #ffff00, #00ff00, #0000ff, #8b00ff);"></div>\n',
    preview: '<div style="height: 3px; margin: 10px 0; background: linear-gradient(to right, #ff0000, #ff7700, #ffff00, #00ff00, #0000ff, #8b00ff);"></div>',
  },
  {
    id: 'divider-leaf',
    name: '树叶分割',
    category: 'divider',
    tags: ['树叶', 'leaf', '自然', '绿色'],
    content: '\n<p style="text-align: center; color: #4caf50; margin: 20px 0; font-size: 16px; letter-spacing: 8px;">🌿🍃🌿🍃🌿🍃🌿</p>\n',
    preview: '<p style="text-align: center; color: #4caf50; margin: 10px 0; font-size: 14px; letter-spacing: 6px;">🌿🍃🌿🍃🌿</p>',
  },
  {
    id: 'divider-heart',
    name: '爱心分割',
    category: 'divider',
    tags: ['爱心', 'heart', '浪漫', '粉色'],
    content: '\n<p style="text-align: center; color: #e91e63; margin: 20px 0; font-size: 14px; letter-spacing: 10px;">♡ ♥ ♡ ♥ ♡ ♥ ♡</p>\n',
    preview: '<p style="text-align: center; color: #e91e63; margin: 10px 0; font-size: 12px; letter-spacing: 8px;">♡ ♥ ♡ ♥ ♡</p>',
  },
  {
    id: 'divider-double-line',
    name: '双线分割',
    category: 'divider',
    tags: ['双线', 'double', '经典'],
    content: '\n<div style="margin: 20px 0; border-top: 3px double #999;"></div>\n',
    preview: '<div style="margin: 10px 0; border-top: 3px double #999;"></div>',
  },
  {
    id: 'divider-sparkle',
    name: '闪光分割',
    category: 'divider',
    tags: ['闪光', 'sparkle', '金色'],
    content: '\n<p style="text-align: center; color: #ffc107; margin: 20px 0; font-size: 16px; letter-spacing: 10px;">✧ ✦ ✧ ✦ ✧ ✦ ✧</p>\n',
    preview: '<p style="text-align: center; color: #ffc107; margin: 10px 0; font-size: 14px; letter-spacing: 8px;">✧ ✦ ✧ ✦ ✧</p>',
  },
  {
    id: 'divider-music',
    name: '音符分割',
    category: 'divider',
    tags: ['音符', 'music', '音乐'],
    content: '\n<p style="text-align: center; color: #9c27b0; margin: 20px 0; font-size: 16px; letter-spacing: 8px;">♪ ♫ ♪ ♫ ♪ ♫ ♪</p>\n',
    preview: '<p style="text-align: center; color: #9c27b0; margin: 10px 0; font-size: 14px; letter-spacing: 6px;">♪ ♫ ♪ ♫ ♪</p>',
  },
  {
    id: 'divider-cloud',
    name: '云朵分割',
    category: 'divider',
    tags: ['云朵', 'cloud', '可爱', '天空'],
    content: '\n<p style="text-align: center; color: #90caf9; margin: 20px 0; font-size: 18px; letter-spacing: 6px;">☁️ ☁️ ☁️ ☁️ ☁️</p>\n',
    preview: '<p style="text-align: center; color: #90caf9; margin: 10px 0; font-size: 14px; letter-spacing: 4px;">☁️ ☁️ ☁️</p>',
  },
  {
    id: 'divider-green-gradient',
    name: '绿色渐变',
    category: 'divider',
    tags: ['绿色', '渐变', '清新'],
    content: '\n<div style="height: 2px; margin: 20px 0; background: linear-gradient(to right, transparent, #4caf50, #81c784, transparent);"></div>\n',
    preview: '<div style="height: 2px; margin: 10px 0; background: linear-gradient(to right, transparent, #4caf50, #81c784, transparent);"></div>',
  },
  {
    id: 'divider-sun',
    name: '太阳分割',
    category: 'divider',
    tags: ['太阳', 'sun', '阳光', '温暖'],
    content: '\n<p style="text-align: center; margin: 20px 0; font-size: 14px; letter-spacing: 6px;">── ☀️ ──</p>\n',
    preview: '<p style="text-align: center; margin: 10px 0; font-size: 12px;">── ☀️ ──</p>',
  },
  {
    id: 'divider-zigzag',
    name: '锯齿分割',
    category: 'divider',
    tags: ['锯齿', 'zigzag', '几何'],
    content: '\n<p style="text-align: center; color: #ff9800; margin: 20px 0; font-size: 14px; letter-spacing: 4px;">▲▽▲▽▲▽▲▽▲▽▲▽</p>\n',
    preview: '<p style="text-align: center; color: #ff9800; margin: 10px 0; font-size: 12px; letter-spacing: 3px;">▲▽▲▽▲▽▲▽</p>',
  },
];

// ============================================================
// 文字装饰块素材
// ============================================================

export const TEXT_BLOCKS: AssetItem[] = [
  {
    id: 'block-info',
    name: '信息提示框',
    category: 'text-block',
    tags: ['提示', 'info', '蓝色', '信息'],
    content: '\n<div style="background: #e3f2fd; border-left: 4px solid #1976d2; padding: 12px 16px; margin: 16px 0; border-radius: 4px; color: #1565c0; font-size: 14px;">💡 <strong style="color: #1565c0;">提示：</strong>在此输入提示内容</div>\n',
    preview: '<div style="background: #e3f2fd; border-left: 4px solid #1976d2; padding: 8px 12px; border-radius: 4px; color: #1565c0; font-size: 12px;">💡 <strong style="color: #1565c0;">提示：</strong>在此输入提示内容</div>',
  },
  {
    id: 'block-warning',
    name: '警告提示框',
    category: 'text-block',
    tags: ['警告', 'warning', '黄色', '注意'],
    content: '\n<div style="background: #fff3e0; border-left: 4px solid #f57c00; padding: 12px 16px; margin: 16px 0; border-radius: 4px; color: #e65100; font-size: 14px;">⚠️ <strong style="color: #e65100;">注意：</strong>在此输入警告内容</div>\n',
    preview: '<div style="background: #fff3e0; border-left: 4px solid #f57c00; padding: 8px 12px; border-radius: 4px; color: #e65100; font-size: 12px;">⚠️ <strong style="color: #e65100;">注意：</strong>在此输入警告内容</div>',
  },
  {
    id: 'block-success',
    name: '成功提示框',
    category: 'text-block',
    tags: ['成功', 'success', '绿色', '完成'],
    content: '\n<div style="background: #e8f5e9; border-left: 4px solid #388e3c; padding: 12px 16px; margin: 16px 0; border-radius: 4px; color: #2e7d32; font-size: 14px;">✅ <strong style="color: #2e7d32;">成功：</strong>在此输入成功内容</div>\n',
    preview: '<div style="background: #e8f5e9; border-left: 4px solid #388e3c; padding: 8px 12px; border-radius: 4px; color: #2e7d32; font-size: 12px;">✅ <strong style="color: #2e7d32;">成功：</strong>在此输入成功内容</div>',
  },
  {
    id: 'block-error',
    name: '错误提示框',
    category: 'text-block',
    tags: ['错误', 'error', '红色', '失败'],
    content: '\n<div style="background: #ffebee; border-left: 4px solid #d32f2f; padding: 12px 16px; margin: 16px 0; border-radius: 4px; color: #c62828; font-size: 14px;">❌ <strong style="color: #c62828;">错误：</strong>在此输入错误内容</div>\n',
    preview: '<div style="background: #ffebee; border-left: 4px solid #d32f2f; padding: 8px 12px; border-radius: 4px; color: #c62828; font-size: 12px;">❌ <strong style="color: #c62828;">错误：</strong>在此输入错误内容</div>',
  },
  {
    id: 'block-steps',
    name: '编号步骤块',
    category: 'text-block',
    tags: ['步骤', 'steps', '编号', '流程'],
    content: '\n<div style="background: #f5f5f5; padding: 16px 20px; margin: 16px 0; border-radius: 8px; font-size: 14px; color: #333;"><div style="margin-bottom: 10px;"><span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; background: #1976d2; color: #fff; border-radius: 50%; font-size: 12px; margin-right: 8px;">1</span><strong style="color: #333;">第一步：</strong>描述步骤内容</div><div style="margin-bottom: 10px;"><span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; background: #1976d2; color: #fff; border-radius: 50%; font-size: 12px; margin-right: 8px;">2</span><strong style="color: #333;">第二步：</strong>描述步骤内容</div><div><span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; background: #1976d2; color: #fff; border-radius: 50%; font-size: 12px; margin-right: 8px;">3</span><strong style="color: #333;">第三步：</strong>描述步骤内容</div></div>\n',
    preview: '<div style="background: #f5f5f5; padding: 8px 12px; border-radius: 6px; font-size: 11px; color: #333;"><span style="display: inline-block; width: 18px; height: 18px; line-height: 18px; text-align: center; background: #1976d2; color: #fff; border-radius: 50%; font-size: 10px; margin-right: 4px;">1</span> 第一步 → <span style="display: inline-block; width: 18px; height: 18px; line-height: 18px; text-align: center; background: #1976d2; color: #fff; border-radius: 50%; font-size: 10px; margin-right: 4px;">2</span> 第二步 → ...</div>',
  },
  {
    id: 'block-quote-highlight',
    name: '高亮引用块',
    category: 'text-block',
    tags: ['引用', 'quote', '高亮', '名言'],
    content: '\n<div style="border-left: 4px solid #ff6f00; background: #fff8e1; padding: 16px 20px; margin: 16px 0; border-radius: 0 8px 8px 0; font-size: 15px; color: #555; font-style: italic; line-height: 1.8;">「在此输入引用内容，可以是名言、金句或重要观点。」<div style="text-align: right; margin-top: 8px; font-size: 13px; color: #999; font-style: normal;">—— 作者名</div></div>\n',
    preview: '<div style="border-left: 3px solid #ff6f00; background: #fff8e1; padding: 8px 12px; border-radius: 0 6px 6px 0; font-size: 11px; color: #555; font-style: italic;">「引用内容...」</div>',
  },
  {
    id: 'block-callout',
    name: '标注框',
    category: 'text-block',
    tags: ['标注', 'callout', '重点', '注释'],
    content: '\n<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px 24px; margin: 16px 0; border-radius: 8px; color: #fff; font-size: 15px; line-height: 1.8;"><div style="font-size: 18px; font-weight: bold; margin-bottom: 8px; color: #fff;">📌 重点标注</div><div style="color: rgba(255,255,255,0.9);">在此输入需要重点标注的内容，支持多行文本。</div></div>\n',
    preview: '<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 8px 12px; border-radius: 6px; color: #fff; font-size: 11px;">📌 <strong style="color: #fff;">重点标注</strong></div>',
  },
  {
    id: 'block-number-card',
    name: '数据卡片',
    category: 'text-block',
    tags: ['数据', '数字', '卡片', '统计'],
    content: '\n<div style="display: flex; gap: 12px; margin: 16px 0;"><div style="flex: 1; background: #e3f2fd; padding: 16px; border-radius: 8px; text-align: center;"><div style="font-size: 28px; font-weight: bold; color: #1565c0;">99%</div><div style="font-size: 12px; color: #666; margin-top: 4px;">满意度</div></div><div style="flex: 1; background: #e8f5e9; padding: 16px; border-radius: 8px; text-align: center;"><div style="font-size: 28px; font-weight: bold; color: #2e7d32;">10万+</div><div style="font-size: 12px; color: #666; margin-top: 4px;">用户数</div></div><div style="flex: 1; background: #fff3e0; padding: 16px; border-radius: 8px; text-align: center;"><div style="font-size: 28px; font-weight: bold; color: #e65100;">500+</div><div style="font-size: 12px; color: #666; margin-top: 4px;">合作伙伴</div></div></div>\n',
    preview: '<div style="display: flex; gap: 6px;"><div style="flex: 1; background: #e3f2fd; padding: 6px; border-radius: 4px; text-align: center; font-size: 10px;"><strong style="color: #1565c0;">99%</strong></div><div style="flex: 1; background: #e8f5e9; padding: 6px; border-radius: 4px; text-align: center; font-size: 10px;"><strong style="color: #2e7d32;">10万+</strong></div><div style="flex: 1; background: #fff3e0; padding: 6px; border-radius: 4px; text-align: center; font-size: 10px;"><strong style="color: #e65100;">500+</strong></div></div>',
  },
  {
    id: 'block-timeline',
    name: '时间线',
    category: 'text-block',
    tags: ['时间线', 'timeline', '流程', '历史'],
    content: '\n<div style="padding: 16px 20px; margin: 16px 0; font-size: 14px; color: #333;"><div style="display: flex; margin-bottom: 16px;"><div style="width: 60px; font-weight: bold; color: #1565c0; flex-shrink: 0;">2024</div><div style="border-left: 2px solid #1565c0; padding-left: 16px; position: relative;"><div style="position: absolute; left: -6px; top: 4px; width: 10px; height: 10px; background: #1565c0; border-radius: 50%;"></div>第一个里程碑事件描述</div></div><div style="display: flex; margin-bottom: 16px;"><div style="width: 60px; font-weight: bold; color: #1565c0; flex-shrink: 0;">2025</div><div style="border-left: 2px solid #1565c0; padding-left: 16px; position: relative;"><div style="position: absolute; left: -6px; top: 4px; width: 10px; height: 10px; background: #1565c0; border-radius: 50%;"></div>第二个里程碑事件描述</div></div><div style="display: flex;"><div style="width: 60px; font-weight: bold; color: #1565c0; flex-shrink: 0;">2026</div><div style="border-left: 2px solid #1565c0; padding-left: 16px; position: relative;"><div style="position: absolute; left: -6px; top: 4px; width: 10px; height: 10px; background: #1565c0; border-radius: 50%;"></div>第三个里程碑事件描述</div></div></div>\n',
    preview: '<div style="font-size: 10px; padding: 6px;"><span style="color: #1565c0; font-weight: bold;">2024</span> → <span style="color: #1565c0; font-weight: bold;">2025</span> → <span style="color: #1565c0; font-weight: bold;">2026</span></div>',
  },
  {
    id: 'block-feature-grid',
    name: '功能网格',
    category: 'text-block',
    tags: ['功能', '网格', '特性', '展示'],
    content: '\n<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0;"><div style="background: #f5f5f5; padding: 16px; border-radius: 8px; text-align: center;"><div style="font-size: 28px; margin-bottom: 8px;">🚀</div><div style="font-weight: bold; font-size: 14px; color: #333; margin-bottom: 4px;">快速高效</div><div style="font-size: 12px; color: #666;">功能描述文字</div></div><div style="background: #f5f5f5; padding: 16px; border-radius: 8px; text-align: center;"><div style="font-size: 28px; margin-bottom: 8px;">🔒</div><div style="font-weight: bold; font-size: 14px; color: #333; margin-bottom: 4px;">安全可靠</div><div style="font-size: 12px; color: #666;">功能描述文字</div></div><div style="background: #f5f5f5; padding: 16px; border-radius: 8px; text-align: center;"><div style="font-size: 28px; margin-bottom: 8px;">💡</div><div style="font-weight: bold; font-size: 14px; color: #333; margin-bottom: 4px;">智能便捷</div><div style="font-size: 12px; color: #666;">功能描述文字</div></div><div style="background: #f5f5f5; padding: 16px; border-radius: 8px; text-align: center;"><div style="font-size: 28px; margin-bottom: 8px;">❤️</div><div style="font-weight: bold; font-size: 14px; color: #333; margin-bottom: 4px;">用心服务</div><div style="font-size: 12px; color: #666;">功能描述文字</div></div></div>\n',
    preview: '<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 4px; font-size: 10px;"><div style="background: #f5f5f5; padding: 4px; border-radius: 4px; text-align: center;">🚀 快速</div><div style="background: #f5f5f5; padding: 4px; border-radius: 4px; text-align: center;">🔒 安全</div></div>',
  },
  {
    id: 'block-author-card',
    name: '作者名片',
    category: 'text-block',
    tags: ['作者', '名片', '简介', '关注'],
    content: '\n<div style="background: #f8f9fa; border: 1px solid #e9ecef; padding: 20px; margin: 16px 0; border-radius: 12px; display: flex; align-items: center; gap: 16px;"><div style="width: 60px; height: 60px; border-radius: 50%; background: linear-gradient(135deg, #667eea, #764ba2); display: flex; align-items: center; justify-content: center; font-size: 28px; flex-shrink: 0;">👤</div><div><div style="font-weight: bold; font-size: 16px; color: #333; margin-bottom: 4px;">作者名称</div><div style="font-size: 13px; color: #666; margin-bottom: 8px;">一句话简介，描述你的身份或专长</div><div style="font-size: 12px; color: #1565c0;">关注我，获取更多精彩内容 →</div></div></div>\n',
    preview: '<div style="display: flex; align-items: center; gap: 8px; font-size: 10px; background: #f8f9fa; padding: 6px; border-radius: 6px;">👤 <span><strong>作者名称</strong><br/>一句话简介</span></div>',
  },
  {
    id: 'block-qrcode-footer',
    name: '二维码尾部',
    category: 'text-block',
    tags: ['二维码', '关注', '尾部', '公众号'],
    content: '\n<div style="text-align: center; padding: 24px 20px; margin: 20px 0; background: #f8f9fa; border-radius: 12px;"><div style="font-size: 16px; font-weight: bold; color: #333; margin-bottom: 8px;">扫码关注我们</div><div style="font-size: 13px; color: #666; margin-bottom: 16px;">获取更多精彩内容</div><div style="width: 120px; height: 120px; background: #e0e0e0; margin: 0 auto; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 12px; color: #999;">二维码占位</div><div style="font-size: 12px; color: #999; margin-top: 12px;">长按识别二维码关注</div></div>\n',
    preview: '<div style="text-align: center; font-size: 10px; background: #f8f9fa; padding: 6px; border-radius: 6px;">📱 扫码关注我们</div>',
  },
];

// ============================================================
// Emoji 数据
// ============================================================

export const EMOJIS: EmojiItem[] = [
  // 表情 (faces)
  { char: '😀', name: '笑脸', category: 'faces' },
  { char: '😃', name: '大笑', category: 'faces' },
  { char: '😄', name: '开心', category: 'faces' },
  { char: '😁', name: '嘻嘻', category: 'faces' },
  { char: '😆', name: '斜眼笑', category: 'faces' },
  { char: '😅', name: '苦笑', category: 'faces' },
  { char: '🤣', name: '笑哭', category: 'faces' },
  { char: '😂', name: '喜极而泣', category: 'faces' },
  { char: '🙂', name: '微笑', category: 'faces' },
  { char: '😊', name: '害羞', category: 'faces' },
  { char: '😇', name: '天使', category: 'faces' },
  { char: '🥰', name: '喜爱', category: 'faces' },

  // 手势 (gestures)
  { char: '👍', name: '点赞', category: 'gestures' },
  { char: '👎', name: '踩', category: 'gestures' },
  { char: '👏', name: '鼓掌', category: 'gestures' },
  { char: '🙌', name: '举手', category: 'gestures' },
  { char: '🤝', name: '握手', category: 'gestures' },
  { char: '✌️', name: '胜利', category: 'gestures' },
  { char: '🤞', name: '祈祷', category: 'gestures' },
  { char: '👌', name: 'OK', category: 'gestures' },
  { char: '🤙', name: '打电话', category: 'gestures' },
  { char: '👋', name: '挥手', category: 'gestures' },
  { char: '✋', name: '停止', category: 'gestures' },
  { char: '🖐️', name: '张开手', category: 'gestures' },

  // 动物 (animals)
  { char: '🐶', name: '狗', category: 'animals' },
  { char: '🐱', name: '猫', category: 'animals' },
  { char: '🐭', name: '老鼠', category: 'animals' },
  { char: '🐹', name: '仓鼠', category: 'animals' },
  { char: '🐰', name: '兔子', category: 'animals' },
  { char: '🦊', name: '狐狸', category: 'animals' },
  { char: '🐻', name: '熊', category: 'animals' },
  { char: '🐼', name: '熊猫', category: 'animals' },
  { char: '🐨', name: '考拉', category: 'animals' },
  { char: '🐯', name: '老虎', category: 'animals' },
  { char: '🦁', name: '狮子', category: 'animals' },
  { char: '🐮', name: '牛', category: 'animals' },

  // 食物 (food)
  { char: '🍎', name: '苹果', category: 'food' },
  { char: '🍐', name: '梨', category: 'food' },
  { char: '🍊', name: '橘子', category: 'food' },
  { char: '🍋', name: '柠檬', category: 'food' },
  { char: '🍌', name: '香蕉', category: 'food' },
  { char: '🍉', name: '西瓜', category: 'food' },
  { char: '🍇', name: '葡萄', category: 'food' },
  { char: '🍓', name: '草莓', category: 'food' },
  { char: '🫐', name: '蓝莓', category: 'food' },
  { char: '🍒', name: '樱桃', category: 'food' },
  { char: '🍑', name: '桃子', category: 'food' },
  { char: '🥝', name: '猕猴桃', category: 'food' },

  // 交通 (travel)
  { char: '✈️', name: '飞机', category: 'travel' },
  { char: '🚗', name: '汽车', category: 'travel' },
  { char: '🚕', name: '出租车', category: 'travel' },
  { char: '🚌', name: '公交车', category: 'travel' },
  { char: '🚎', name: '电车', category: 'travel' },
  { char: '🏎️', name: '赛车', category: 'travel' },
  { char: '🚓', name: '警车', category: 'travel' },
  { char: '🚑', name: '救护车', category: 'travel' },
  { char: '🚒', name: '消防车', category: 'travel' },
  { char: '🚐', name: '面包车', category: 'travel' },
  { char: '🛻', name: '皮卡', category: 'travel' },
  { char: '🚚', name: '货车', category: 'travel' },

  // 物品 (objects)
  { char: '💻', name: '笔记本', category: 'objects' },
  { char: '📱', name: '手机', category: 'objects' },
  { char: '⌨️', name: '键盘', category: 'objects' },
  { char: '🖥️', name: '台式机', category: 'objects' },
  { char: '🖨️', name: '打印机', category: 'objects' },
  { char: '📷', name: '相机', category: 'objects' },
  { char: '📹', name: '摄像机', category: 'objects' },
  { char: '🎥', name: '电影', category: 'objects' },
  { char: '📺', name: '电视', category: 'objects' },
  { char: '📻', name: '收音机', category: 'objects' },
  { char: '🔋', name: '电池', category: 'objects' },
  { char: '💡', name: '灯泡', category: 'objects' },

  // 符号 (symbols)
  { char: '❤️', name: '红心', category: 'symbols' },
  { char: '🧡', name: '橙心', category: 'symbols' },
  { char: '💛', name: '黄心', category: 'symbols' },
  { char: '💚', name: '绿心', category: 'symbols' },
  { char: '💙', name: '蓝心', category: 'symbols' },
  { char: '💜', name: '紫心', category: 'symbols' },
  { char: '🖤', name: '黑心', category: 'symbols' },
  { char: '🤍', name: '白心', category: 'symbols' },
  { char: '✨', name: '闪光', category: 'symbols' },
  { char: '⭐', name: '星星', category: 'symbols' },
  { char: '🌟', name: '发光星', category: 'symbols' },
  { char: '💫', name: '头晕', category: 'symbols' },
];

// ============================================================
// GIF 动图素材
// ============================================================

export const GIFS: AssetItem[] = [
  {
    id: 'gif-thumbs-up',
    name: '竖大拇指',
    category: 'gif',
    tags: ['点赞', '大拇指', '好的', '赞', 'thumbs up'],
    content: '\n<img src="https://media.giphy.com/media/111ebonMs90YLu/giphy.gif" alt="竖大拇指" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/111ebonMs90YLu/200w.gif" alt="竖大拇指" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-clap',
    name: '鼓掌',
    category: 'gif',
    tags: ['鼓掌', '掌声', '厉害', 'clap', '棒'],
    content: '\n<img src="https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif" alt="鼓掌" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/NEvPzZ8bd1V4Y/200w.gif" alt="鼓掌" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-celebrate',
    name: '庆祝撒花',
    category: 'gif',
    tags: ['庆祝', '撒花', '开心', '派对', 'celebrate'],
    content: '\n<img src="https://media.giphy.com/media/g9582DNuQppxC/giphy.gif" alt="庆祝撒花" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/g9582DNuQppxC/200w.gif" alt="庆祝撒花" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-mind-blown',
    name: '脑洞大开',
    category: 'gif',
    tags: ['震惊', '脑洞', '惊讶', 'mind blown', '厉害'],
    content: '\n<img src="https://media.giphy.com/media/xT0xeJpnrWC3XWblEk/giphy.gif" alt="脑洞大开" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/xT0xeJpnrWC3XWblEk/200w.gif" alt="脑洞大开" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-typing',
    name: '疯狂打字',
    category: 'gif',
    tags: ['打字', '工作', '忙碌', 'typing', '码字'],
    content: '\n<img src="https://media.giphy.com/media/LmNwrBhejkK9EFP504/giphy.gif" alt="疯狂打字" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/LmNwrBhejkK9EFP504/200w.gif" alt="疯狂打字" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-thinking',
    name: '思考中',
    category: 'gif',
    tags: ['思考', '想', '嗯', 'thinking', '疑问'],
    content: '\n<img src="https://media.giphy.com/media/a5viI92PAF89q/giphy.gif" alt="思考中" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/a5viI92PAF89q/200w.gif" alt="思考中" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-wow',
    name: '哇哦',
    category: 'gif',
    tags: ['哇', '惊叹', '厉害', 'wow', '震惊'],
    content: '\n<img src="https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif" alt="哇哦" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/200w.gif" alt="哇哦" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-dance',
    name: '跳舞',
    category: 'gif',
    tags: ['跳舞', '开心', '嗨', 'dance', '快乐'],
    content: '\n<img src="https://media.giphy.com/media/l0HlNQ03J5JxX6lva/giphy.gif" alt="跳舞" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/l0HlNQ03J5JxX6lva/200w.gif" alt="跳舞" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-fire',
    name: '燃起来了',
    category: 'gif',
    tags: ['火', '燃', '热门', 'fire', '厉害'],
    content: '\n<img src="https://media.giphy.com/media/j2pOGeGYKe2xCCKwfi/giphy.gif" alt="燃起来了" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/j2pOGeGYKe2xCCKwfi/200w.gif" alt="燃起来了" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-love',
    name: '比心',
    category: 'gif',
    tags: ['爱', '比心', '喜欢', 'love', '心'],
    content: '\n<img src="https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif" alt="比心" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/26BRv0ThflsHCqDrG/200w.gif" alt="比心" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-rocket',
    name: '火箭发射',
    category: 'gif',
    tags: ['火箭', '发射', '起飞', 'rocket', '冲'],
    content: '\n<img src="https://media.giphy.com/media/mi6DsSSNKDbUY/giphy.gif" alt="火箭发射" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/mi6DsSSNKDbUY/200w.gif" alt="火箭发射" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
  {
    id: 'gif-coffee',
    name: '喝咖啡',
    category: 'gif',
    tags: ['咖啡', '喝', '休息', 'coffee', '摸鱼'],
    content: '\n<img src="https://media.giphy.com/media/drj6PcnAMfJ7O/giphy.gif" alt="喝咖啡" style="max-width: 200px; border-radius: 8px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/drj6PcnAMfJ7O/200w.gif" alt="喝咖啡" style="width: 80px; height: 60px; object-fit: cover; border-radius: 6px;" />',
  },
];

// ============================================================
// 可爱搞怪表情包素材
// ============================================================

export const STICKERS: AssetItem[] = [
  {
    id: 'sticker-cat-cute',
    name: '可爱猫咪',
    category: 'sticker',
    tags: ['猫', '可爱', '萌', 'cute', 'cat'],
    content: '\n<img src="https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif" alt="可爱猫咪" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/JIX9t2j0ZTN9S/200w.gif" alt="可爱猫咪" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-dog-shake',
    name: '狗狗摇头',
    category: 'sticker',
    tags: ['狗', '摇头', '搞笑', 'dog', '可爱'],
    content: '\n<img src="https://media.giphy.com/media/4Zo41lhzKt6iZ8xff9/giphy.gif" alt="狗狗摇头" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/4Zo41lhzKt6iZ8xff9/200w.gif" alt="狗狗摇头" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-panda-roll',
    name: '熊猫打滚',
    category: 'sticker',
    tags: ['熊猫', '打滚', '可爱', 'panda', '搞笑'],
    content: '\n<img src="https://media.giphy.com/media/EatwJZRUIv41G/giphy.gif" alt="熊猫打滚" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/EatwJZRUIv41G/200w.gif" alt="熊猫打滚" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-bunny-peek',
    name: '兔子偷看',
    category: 'sticker',
    tags: ['兔子', '偷看', '害羞', 'bunny', '可爱'],
    content: '\n<img src="https://media.giphy.com/media/xUPGcMzfkOPknzp3kQ/giphy.gif" alt="兔子偷看" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/xUPGcMzfkOPknzp3kQ/200w.gif" alt="兔子偷看" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-cat-typing',
    name: '猫咪打字',
    category: 'sticker',
    tags: ['猫', '打字', '工作', '搞笑', 'typing cat'],
    content: '\n<img src="https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif" alt="猫咪打字" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/JIX9t2j0ZTN9S/200w.gif" alt="猫咪打字" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-frog-sip',
    name: '青蛙喝茶',
    category: 'sticker',
    tags: ['青蛙', '喝茶', '淡定', 'frog', '搞怪'],
    content: '\n<img src="https://media.giphy.com/media/kFgzrTt798d2w/giphy.gif" alt="青蛙喝茶" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/kFgzrTt798d2w/200w.gif" alt="青蛙喝茶" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-shiba-wow',
    name: '柴犬惊讶',
    category: 'sticker',
    tags: ['柴犬', '惊讶', 'doge', 'shiba', '搞笑'],
    content: '\n<img src="https://media.giphy.com/media/9rtpurjbqiqZXbBBet/giphy.gif" alt="柴犬惊讶" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/9rtpurjbqiqZXbBBet/200w.gif" alt="柴犬惊讶" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-penguin-dance',
    name: '企鹅跳舞',
    category: 'sticker',
    tags: ['企鹅', '跳舞', '可爱', 'penguin', '开心'],
    content: '\n<img src="https://media.giphy.com/media/berTqWdVEbcOY/giphy.gif" alt="企鹅跳舞" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/berTqWdVEbcOY/200w.gif" alt="企鹅跳舞" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-cat-heart',
    name: '猫咪比心',
    category: 'sticker',
    tags: ['猫', '比心', '爱', 'heart', '可爱'],
    content: '\n<img src="https://media.giphy.com/media/MDJ9IbxxvDUQM/giphy.gif" alt="猫咪比心" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/MDJ9IbxxvDUQM/200w.gif" alt="猫咪比心" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-hamster-eat',
    name: '仓鼠吃东西',
    category: 'sticker',
    tags: ['仓鼠', '吃', '可爱', 'hamster', '萌'],
    content: '\n<img src="https://media.giphy.com/media/rGOPHBBQ3ESYA/giphy.gif" alt="仓鼠吃东西" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/rGOPHBBQ3ESYA/200w.gif" alt="仓鼠吃东西" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-duck-dance',
    name: '鸭子摇摆',
    category: 'sticker',
    tags: ['鸭子', '摇摆', '搞笑', 'duck', '跳舞'],
    content: '\n<img src="https://media.giphy.com/media/sIPfJfe2MbFDO/giphy.gif" alt="鸭子摇摆" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/sIPfJfe2MbFDO/200w.gif" alt="鸭子摇摆" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-bear-wave',
    name: '小熊挥手',
    category: 'sticker',
    tags: ['熊', '挥手', '你好', 'bear', '可爱'],
    content: '\n<img src="https://media.giphy.com/media/IThjAlJnD9WNO/giphy.gif" alt="小熊挥手" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/IThjAlJnD9WNO/200w.gif" alt="小熊挥手" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-cat-nope',
    name: '猫咪拒绝',
    category: 'sticker',
    tags: ['猫', '拒绝', '不要', 'nope', '搞笑'],
    content: '\n<img src="https://media.giphy.com/media/wpoLqr5FT1sY0/giphy.gif" alt="猫咪拒绝" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/wpoLqr5FT1sY0/200w.gif" alt="猫咪拒绝" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-corgi-butt',
    name: '柯基屁股',
    category: 'sticker',
    tags: ['柯基', '屁股', '可爱', 'corgi', '搞笑'],
    content: '\n<img src="https://media.giphy.com/media/mCRJDo24UvJMA/giphy.gif" alt="柯基屁股" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/mCRJDo24UvJMA/200w.gif" alt="柯基屁股" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-owl-blink',
    name: '猫头鹰眨眼',
    category: 'sticker',
    tags: ['猫头鹰', '眨眼', '呆萌', 'owl', '可爱'],
    content: '\n<img src="https://media.giphy.com/media/Nx85vtTY70T3W/giphy.gif" alt="猫头鹰眨眼" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/Nx85vtTY70T3W/200w.gif" alt="猫头鹰眨眼" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
  {
    id: 'sticker-sloth-chill',
    name: '树懒躺平',
    category: 'sticker',
    tags: ['树懒', '躺平', '摸鱼', 'sloth', '搞笑'],
    content: '\n<img src="https://media.giphy.com/media/3oKIPbNb1vWdftiVLq/giphy.gif" alt="树懒躺平" style="max-width: 150px; border-radius: 12px; margin: 8px 0;" />\n',
    preview: '<img src="https://media.giphy.com/media/3oKIPbNb1vWdftiVLq/200w.gif" alt="树懒躺平" style="width: 70px; height: 70px; object-fit: cover; border-radius: 8px;" />',
  },
];

// ============================================================
// 图片分类与 Unsplash URL 构建
// ============================================================

/** 图片分类中文名映射 */
export const IMAGE_CATEGORY_NAMES: Record<ImageCategory, string> = {
  technology: '科技',
  business: '商务',
  nature: '自然',
  food: '美食',
  city: '城市',
  people: '人物',
  abstract: '抽象',
};

/**
 * 构建 Unsplash 图片直链 URL。
 * 使用真实 Unsplash photo ID，图片内容与描述精确匹配。
 */
function unsplashUrl(photoId: string, width: number): string {
  return `https://images.unsplash.com/${photoId}?w=${width}&fit=crop&auto=format&q=80`;
}

/** 根据 Unsplash photo ID 构建图片素材 */
function buildImageAsset(
  category: ImageCategory,
  id: string,
  name: string,
  photoId: string,
  alt: string,
): ImageAsset {
  return {
    id,
    name,
    category,
    thumbnailUrl: unsplashUrl(photoId, 400),
    fullUrl: unsplashUrl(photoId, 1080),
    alt,
  };
}

/** 所有图片分类的预定义素材（每分类 10 张，共 70 张） */
export const IMAGE_ASSETS: Record<ImageCategory, ImageAsset[]> = {
  technology: [
    buildImageAsset('technology', 'img-tech-01', '笔记本电脑', 'photo-1496181133206-80ce9b88a853', '银色笔记本电脑放在桌面上'),
    buildImageAsset('technology', 'img-tech-02', '编程代码', 'photo-1461749280684-dccba630e2f6', '屏幕上的编程代码'),
    buildImageAsset('technology', 'img-tech-03', '服务器机房', 'photo-1558494949-ef010cbdcc31', '数据中心服务器机架'),
    buildImageAsset('technology', 'img-tech-04', '电路板', 'photo-1518770660439-4636190af475', '绿色电路板微距特写'),
    buildImageAsset('technology', 'img-tech-05', '智能手机', 'photo-1511707171634-5f897ff02aa9', '手持智能手机'),
    buildImageAsset('technology', 'img-tech-06', 'VR 头盔', 'photo-1592478411213-6153e4ebc07d', '佩戴 VR 头盔的人'),
    buildImageAsset('technology', 'img-tech-07', '机械键盘', 'photo-1595225476474-87563907a212', 'RGB 机械键盘'),
    buildImageAsset('technology', 'img-tech-08', '无人机', 'photo-1473968512647-3e447244af8f', '飞行中的无人机'),
    buildImageAsset('technology', 'img-tech-09', '3D 打印', 'photo-1581092160607-ee22621dd758', '3D 打印机工作中'),
    buildImageAsset('technology', 'img-tech-10', '芯片', 'photo-1555617981-dac3880eac6e', '微处理器芯片特写'),
  ],
  business: [
    buildImageAsset('business', 'img-biz-01', '办公室', 'photo-1497366216548-37526070297c', '现代开放式办公室'),
    buildImageAsset('business', 'img-biz-02', '商务会议', 'photo-1552664730-d307ca884978', '团队围坐会议桌讨论'),
    buildImageAsset('business', 'img-biz-03', '握手', 'photo-1521791136064-7986c2920216', '两人商务握手'),
    buildImageAsset('business', 'img-biz-04', '数据图表', 'photo-1551288049-bebda4e38f71', '屏幕上的数据分析图表'),
    buildImageAsset('business', 'img-biz-05', '团队协作', 'photo-1522071820081-009f0129c71c', '团队围坐讨论项目'),
    buildImageAsset('business', 'img-biz-06', '演讲', 'photo-1475721027785-f74eccf877e2', '商务演讲现场'),
    buildImageAsset('business', 'img-biz-07', '白板头脑风暴', 'photo-1531538606174-e1ed1e26f680', '白板上的头脑风暴'),
    buildImageAsset('business', 'img-biz-08', '咖啡办公', 'photo-1497215842964-222b430dc094', '咖啡馆中使用笔记本办公'),
    buildImageAsset('business', 'img-biz-09', '签合同', 'photo-1450101499163-c8848c66ca85', '签署商务合同'),
    buildImageAsset('business', 'img-biz-10', '创业公司', 'photo-1559136555-9303baea8ebd', '创业团队工作场景'),
  ],
  nature: [
    buildImageAsset('nature', 'img-nat-01', '雪山', 'photo-1464822759023-fed622ff2c3b', '壮丽的雪山风景'),
    buildImageAsset('nature', 'img-nat-02', '海洋', 'photo-1505118380757-91f5f5632de0', '蔚蓝的海洋和海浪'),
    buildImageAsset('nature', 'img-nat-03', '森林', 'photo-1448375240586-882707db888b', '阳光穿过茂密的森林'),
    buildImageAsset('nature', 'img-nat-04', '日落', 'photo-1495616811223-4d98c6e9c869', '海边金色日落'),
    buildImageAsset('nature', 'img-nat-05', '花卉', 'photo-1490750967868-88aa4f44baee', '盛开的粉色花朵'),
    buildImageAsset('nature', 'img-nat-06', '瀑布', 'photo-1432405972618-c6b0cfba8b3e', '壮观的瀑布'),
    buildImageAsset('nature', 'img-nat-07', '湖泊', 'photo-1439066615861-d1af74d74000', '平静的山间湖泊'),
    buildImageAsset('nature', 'img-nat-08', '星空', 'photo-1519681393784-d120267933ba', '璀璨的星空银河'),
    buildImageAsset('nature', 'img-nat-09', '秋叶', 'photo-1507003211169-0a1dd7228f2d', '金黄色的秋天树叶'),
    buildImageAsset('nature', 'img-nat-10', '沙漠', 'photo-1509316785289-025f5b846b35', '广阔的沙漠沙丘'),
  ],
  food: [
    buildImageAsset('food', 'img-food-01', '咖啡', 'photo-1495474472287-4d71bcdd2085', '拿铁咖啡拉花'),
    buildImageAsset('food', 'img-food-02', '寿司', 'photo-1579871494447-9811cf80d66c', '精致的日式寿司拼盘'),
    buildImageAsset('food', 'img-food-03', '披萨', 'photo-1565299624946-b28f40a0ae38', '新鲜出炉的意式披萨'),
    buildImageAsset('food', 'img-food-04', '沙拉', 'photo-1512621776951-a57141f2eefd', '新鲜蔬菜沙拉'),
    buildImageAsset('food', 'img-food-05', '蛋糕', 'photo-1578985545062-69928b1d9587', '精美的巧克力蛋糕'),
    buildImageAsset('food', 'img-food-06', '水果', 'photo-1619566636858-adf3ef46400b', '新鲜水果拼盘'),
    buildImageAsset('food', 'img-food-07', '汉堡', 'photo-1568901346375-23c9450c58cd', '多汁的牛肉汉堡'),
    buildImageAsset('food', 'img-food-08', '面包', 'photo-1509440159596-0249088772ff', '新鲜烘焙的面包'),
    buildImageAsset('food', 'img-food-09', '冰淇淋', 'photo-1497034825429-c343d7c6a68f', '彩色冰淇淋球'),
    buildImageAsset('food', 'img-food-10', '中餐', 'photo-1563245372-f21724e3856d', '色香味俱全的中式菜肴'),
  ],
  city: [
    buildImageAsset('city', 'img-city-01', '城市天际线', 'photo-1477959858617-67f85cf4f1df', '城市高楼天际线'),
    buildImageAsset('city', 'img-city-02', '街道', 'photo-1519501025264-65ba15a82390', '繁华的城市街道'),
    buildImageAsset('city', 'img-city-03', '桥梁', 'photo-1474044159687-1ee9f3a51722', '城市大桥夜景'),
    buildImageAsset('city', 'img-city-04', '摩天大楼', 'photo-1486325212027-8081e485255e', '仰视摩天大楼'),
    buildImageAsset('city', 'img-city-05', '城市夜景', 'photo-1514565131-fce0801e5785', '灯火辉煌的城市夜景'),
    buildImageAsset('city', 'img-city-06', '地铁', 'photo-1474487548417-781cb71495f3', '地铁站台'),
    buildImageAsset('city', 'img-city-07', '公园', 'photo-1501594907352-04cda38ebc29', '城市中心公园'),
    buildImageAsset('city', 'img-city-08', '老城区', 'photo-1480714378408-67cf0d13bc1b', '欧式老城区街景'),
    buildImageAsset('city', 'img-city-09', '霓虹灯', 'photo-1542051841857-5f90071e7989', '东京霓虹灯街道'),
    buildImageAsset('city', 'img-city-10', '航拍城市', 'photo-1449824913935-59a10b8d2000', '航拍城市全景'),
  ],
  people: [
    buildImageAsset('people', 'img-ppl-01', '肖像', 'photo-1507003211169-0a1dd7228f2d', '自信的男性肖像'),
    buildImageAsset('people', 'img-ppl-02', '团队合影', 'photo-1529156069898-49953e39b3ac', '开心的团队合影'),
    buildImageAsset('people', 'img-ppl-03', '阅读', 'photo-1506880018603-83d5b814b5a6', '安静阅读的人'),
    buildImageAsset('people', 'img-ppl-04', '运动', 'photo-1476480862126-209bfaa8edc8', '户外跑步运动'),
    buildImageAsset('people', 'img-ppl-05', '工作中', 'photo-1521737711867-e3b97375f902', '专注工作的人'),
    buildImageAsset('people', 'img-ppl-06', '旅行', 'photo-1501785888041-af3ef285b470', '背包旅行者看风景'),
    buildImageAsset('people', 'img-ppl-07', '音乐', 'photo-1511671782779-c97d3d27a1d4', '弹吉他的音乐人'),
    buildImageAsset('people', 'img-ppl-08', '烹饪', 'photo-1556910103-1c02745aae4d', '厨房中烹饪的人'),
    buildImageAsset('people', 'img-ppl-09', '瑜伽', 'photo-1544367567-0f2fcb009e0b', '户外瑜伽练习'),
    buildImageAsset('people', 'img-ppl-10', '摄影师', 'photo-1554048612-b6a482bc67e5', '拿着相机的摄影师'),
  ],
  abstract: [
    buildImageAsset('abstract', 'img-abs-01', '流体渐变', 'photo-1557672172-298e090bd0f1', '彩色流体渐变背景'),
    buildImageAsset('abstract', 'img-abs-02', '几何图形', 'photo-1509228468518-180dd4864904', '彩色几何图形组合'),
    buildImageAsset('abstract', 'img-abs-03', '光线', 'photo-1507400492013-162706c8c05e', '抽象光线效果'),
    buildImageAsset('abstract', 'img-abs-04', '水墨', 'photo-1541701494587-cb58502866ab', '水墨扩散效果'),
    buildImageAsset('abstract', 'img-abs-05', '纹理', 'photo-1558591710-4b4a1ae0f04d', '大理石纹理'),
    buildImageAsset('abstract', 'img-abs-06', '波浪', 'photo-1550684376-efcbd6e3f031', '抽象波浪线条'),
    buildImageAsset('abstract', 'img-abs-07', '气泡', 'photo-1558470598-a5dda9640f68', '彩色气泡'),
    buildImageAsset('abstract', 'img-abs-08', '烟雾', 'photo-1511447333015-45b65e60f6d5', '彩色烟雾效果'),
    buildImageAsset('abstract', 'img-abs-09', '棱镜', 'photo-1543722530-d2c3201371e7', '棱镜光谱色彩'),
    buildImageAsset('abstract', 'img-abs-10', '极简线条', 'photo-1494438639946-1ebd1d20bf85', '极简抽象线条'),
  ],
};
